import { useState, useEffect } from "react";
import { useRoute } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { 
  ArrowLeft, 
  Clock, 
  DollarSign, 
  Star, 
  Shield, 
  ExternalLink,
  Download,
  Share2,
  CheckCircle,
  AlertTriangle,
  ChevronLeft,
  ChevronRight,
  Wrench,
  List,
  Zap
} from "lucide-react";
// Header/Footer are provided by AppShell
import { ProjectRating } from "@/components/project-rating";
import { ProjectImage } from "@/components/project-image";
import { FeedbackForm } from "@/components/feedback-form";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import type { ProjectWithInstructions } from "@/lib/types";

export default function ProjectDetail() {
  const [match, params] = useRoute("/project/:id");
  const projectId = params?.id ? parseInt(params.id) : null;
  const { toast } = useToast();
  const [currentStep, setCurrentStep] = useState(0);

  const { data: projectData, isLoading } = useQuery<ProjectWithInstructions>({
    queryKey: ['/api/projects', projectId],
    enabled: !!projectId,
  });

  useEffect(() => {
    setCurrentStep(0);
  }, [projectData]);

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${projectData?.project.title} - Snap Builder AI`,
          text: `Check out this DIY build plan: ${projectData?.project.title}`,
          url: window.location.href,
        });
      } catch {
        await navigator.clipboard.writeText(window.location.href);
        toast({ title: "Link Copied!", description: "Project link copied to clipboard." });
      }
    } else {
      await navigator.clipboard.writeText(window.location.href);
      toast({ title: "Link Copied!", description: "Project link copied to clipboard." });
    }
  };

  const handleDownload = () => {
    if (!projectData) return;
    const { project, instructions } = projectData;
    const content = [
      `${project.title}`,
      `${'='.repeat(project.title.length)}`,
      ``,
      `Category: ${project.category}`,
      `Difficulty: ${project.difficulty}`,
      `Estimated Time: ${project.estimatedTime} minutes`,
      `Estimated Cost: $${project.estimatedCost}`,
      ``,
      `Materials Needed:`,
      project.materials.map(m => `  • ${m.name} (${m.quantity}) — $${m.estimatedCost}`).join('\n'),
      ``,
      `Tools Required:`,
      project.tools.map(t => `  • ${t}`).join('\n'),
      ``,
      project.safetyNotes ? `Safety Notes:\n  ⚠️ ${project.safetyNotes}` : '',
      ``,
      `Step-by-Step Instructions:`,
      `${'='.repeat(28)}`,
      ...instructions.map(inst => [
        ``,
        `Step ${inst.stepNumber}: ${inst.title}`,
        `${'-'.repeat(inst.title.length + 10)}`,
        inst.description,
        inst.safetyWarning ? `⚠️ Safety Warning: ${inst.safetyWarning}` : '',
        inst.adultSupervision ? '👷 Adult supervision recommended for this step.' : ''
      ].filter(Boolean).join('\n')),
      ``,
      `— Generated by Snap Builder AI —`,
      `  https://snapbuilderai-production.up.railway.app`
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_build_plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: "Downloaded!", description: "Build plan saved to your device." });
  };

  // theme now uses semantic tokens via Tailwind (bg-background, text-foreground)


  if (!match || !projectId) {
    return (
      <div className="mx-auto max-w-4xl px-4 py-16 text-center">
        <p className="text-muted-foreground">Project not found.</p>
        <Button onClick={() => window.history.back()} className="mt-4 min-h-11">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back
        </Button>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="mx-auto max-w-4xl px-4 py-16 text-center">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-muted rounded w-1/3 mx-auto"></div>
          <div className="h-64 bg-muted rounded"></div>
          <div className="h-4 bg-muted rounded"></div>
          <div className="h-4 bg-muted rounded w-3/4 mx-auto"></div>
        </div>
      </div>
    );
  }

  if (!projectData) {
    return (
      <div className="mx-auto max-w-4xl px-4 py-16 text-center">
        <p className="text-muted-foreground">Project not found.</p>
        <Button onClick={() => window.history.back()} className="mt-4 min-h-11">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back
        </Button>
      </div>
    );
  }

  const { project, instructions } = projectData;

  const difficultyColor =
    project.difficulty === 'Easy' ? 'bg-green-500/15 text-green-400 border-0' :
    project.difficulty === 'Medium' ? 'bg-yellow-500/15 text-yellow-400 border-0' :
    'bg-red-500/15 text-red-400 border-0';

  return (
    <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        {/* Back Button */}
        <Button
          variant="ghost"
          className="mb-6 text-muted-foreground hover:text-foreground hover:bg-muted"
          onClick={() => window.history.back()}
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>

        {/* Hero Card */}
        <div className="card-premium rounded-2xl overflow-hidden mb-8">
          {/* Project Image */}
          <div className="aspect-video bg-muted relative overflow-hidden">
            <ProjectImage
              imageUrl={project.imageUrl}
              title={project.title}
              className="w-full h-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent" />
            <div className="absolute top-4 right-4 flex gap-2">
              {(project.totalRatings || 0) > 0 && (
                <span className="badge-premium rounded-full px-3 py-1 text-xs font-semibold">
                  {project.ratingPercentage}% Success
                </span>
              )}
              <Badge className={difficultyColor}>
                <Star className="w-3 h-3 mr-1" />
                {project.difficulty}
              </Badge>
            </div>
            <div className="absolute bottom-4 left-4 right-4">
              <h1 className="font-display text-2xl sm:text-3xl font-extrabold text-white leading-tight">
                {project.title}
              </h1>
            </div>
          </div>

          {/* Project Meta */}
          <div className="p-6 border-t border-border">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <div className="flex flex-wrap items-center gap-3">
                <Badge variant="outline" className="text-xs">
                  {project.category}
                </Badge>
                <div className="flex items-center gap-1 text-muted-foreground text-sm">
                  <Clock className="w-4 h-4 text-primary" />
                  <span>{project.estimatedTime} min</span>
                </div>
                {project.estimatedCost && (
                  <div className="flex items-center gap-1 text-orange-400 font-semibold text-sm">
                    <DollarSign className="w-4 h-4" />
                    <span>{project.estimatedCost}</span>
                  </div>
                )}
                {(project.totalRatings || 0) > 0 && (
                  <ProjectRating
                    averageRating={project.averageRating}
                    totalRatings={project.totalRatings}
                    ratingPercentage={project.ratingPercentage}
                    size="sm"
                  />
                )}
              </div>

              {/* Action Buttons */}
              <div className="flex gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleShare}
                  className="text-white/50 hover:text-white hover:bg-white/8 border border-white/10"
                >
                  <Share2 className="w-4 h-4 mr-1.5" />
                  Share
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDownload}
                  className="text-white/50 hover:text-white hover:bg-white/8 border border-white/10"
                >
                  <Download className="w-4 h-4 mr-1.5" />
                  Download
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* Safety Notice */}
        {project.safetyNotes && (
          <div className="bg-amber-500/8 border border-amber-500/20 rounded-xl p-4 mb-6 flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-amber-300 font-semibold text-sm mb-0.5">Safety Notes</p>
              <p className="text-amber-200/70 text-sm">{project.safetyNotes}</p>
            </div>
          </div>
        )}

        {/* Stats Row */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          {[
            { icon: Clock, label: 'Est. Time', value: `${project.estimatedTime} min`, color: 'text-blue-400' },
            { icon: DollarSign, label: 'Est. Cost', value: project.estimatedCost ? `$${project.estimatedCost}` : 'Varies', color: 'text-orange-400' },
            { icon: Shield, label: 'Difficulty', value: project.difficulty, color: 'text-green-400' },
          ].map(({ icon: Icon, label, value, color }) => (
            <div key={label} className="card-premium rounded-xl p-4 text-center">
              <Icon className={`w-6 h-6 ${color} mx-auto mb-2`} />
              <p className="text-white/40 text-xs mb-1">{label}</p>
              <p className="text-white font-semibold text-sm">{value}</p>
            </div>
          ))}
        </div>

        {/* Materials & Tools */}
        <div className="grid md:grid-cols-2 gap-6 mb-8">
          {/* Materials */}
          <div className="card-premium rounded-xl p-6">
            <h3 className="font-display text-white font-bold text-base mb-4 flex items-center gap-2">
              <List className="w-4 h-4 text-orange-400" />
              Materials Needed
            </h3>
            <div className="space-y-3">
              {project.materials.map((material, i) => (
                <div key={i} className="flex items-center justify-between p-3 bg-white/3 rounded-lg border border-white/5">
                  <div className="flex items-center gap-2 flex-1 min-w-0">
                    <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                    <div className="min-w-0">
                      <p className="text-white/90 text-sm font-medium truncate">{material.name}</p>
                      <p className="text-white/40 text-xs">Qty: {material.quantity}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 ml-3 flex-shrink-0">
                    <span className="text-orange-400 text-sm font-semibold">${typeof material.estimatedCost === 'number' ? material.estimatedCost.toFixed(2) : material.estimatedCost}</span>
                    {material.affiliateLink && (
                      <a
                        href={material.affiliateLink}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-400 hover:text-blue-300 transition-colors"
                      >
                        <ExternalLink className="w-3.5 h-3.5" />
                      </a>
                    )}
                  </div>
                </div>
              ))}
              {project.estimatedCost && (
                <div className="border-t border-white/8 pt-3 mt-2 flex justify-between items-center">
                  <span className="text-white/60 text-sm">Total Estimated Cost</span>
                  <span className="text-orange-400 font-bold">${project.estimatedCost}</span>
                </div>
              )}
            </div>
          </div>

          {/* Tools */}
          <div className="card-premium rounded-xl p-6">
            <h3 className="font-display text-white font-bold text-base mb-4 flex items-center gap-2">
              <Wrench className="w-4 h-4 text-blue-400" />
              Tools Required
            </h3>
            <div className="space-y-2">
              {project.tools.map((tool, i) => (
                <div key={i} className="flex items-center gap-2 p-3 bg-white/3 rounded-lg border border-white/5">
                  <div className="w-1.5 h-1.5 bg-blue-400 rounded-full flex-shrink-0" />
                  <span className="text-white/80 text-sm capitalize">{tool}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Step-by-Step Instructions */}
        <div className="card-premium rounded-xl p-6 mb-8">
          <h3 className="font-display text-white font-bold text-lg mb-2 flex items-center gap-2">
            <List className="w-5 h-5 text-orange-400" />
            Step-by-Step Build Plan
          </h3>
          <p className="text-white/40 text-sm mb-6">Follow each step carefully for the best results.</p>

          <div className="space-y-4">
            {instructions.map((instruction, index) => (
              <div
                key={instruction.id}
                className={`relative flex gap-4 p-5 rounded-xl border transition-all duration-200 cursor-pointer ${
                  index === currentStep
                    ? 'bg-orange-500/8 border-orange-500/30'
                    : 'bg-white/2 border-white/6 hover:bg-white/4'
                }`}
                onClick={() => setCurrentStep(index)}
              >
                {/* Step Number */}
                <div className="flex-shrink-0">
                  <div className={`w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold transition-all ${
                    index === currentStep
                      ? 'orange-gradient text-white'
                      : 'bg-white/8 text-white/50'
                  }`}>
                    {instruction.stepNumber}
                  </div>
                </div>

                <div className="flex-1 min-w-0">
                  <h4 className={`font-semibold mb-1 text-sm ${index === currentStep ? 'text-white' : 'text-white/70'}`}>
                    {instruction.title}
                  </h4>
                  <p className={`text-sm leading-relaxed ${index === currentStep ? 'text-white/70' : 'text-white/40'}`}>
                    {instruction.description}
                  </p>

                  {instruction.safetyWarning && (
                    <div className="mt-3 flex items-start gap-2 bg-red-500/8 border border-red-500/20 rounded-lg p-3">
                      <AlertTriangle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                      <p className="text-red-300/80 text-xs">{instruction.safetyWarning}</p>
                    </div>
                  )}

                  {instruction.adultSupervision && (
                    <div className="mt-3 flex items-center gap-2 bg-blue-500/8 border border-blue-500/20 rounded-lg p-3">
                      <Shield className="w-4 h-4 text-blue-400 flex-shrink-0" />
                      <p className="text-blue-300/80 text-xs">Adult supervision recommended for this step.</p>
                    </div>
                  )}
                </div>

                {/* Connector line */}
                {index < instructions.length - 1 && (
                  <div className="absolute left-[2.45rem] top-[3.8rem] w-px h-4 bg-white/10" />
                )}
              </div>
            ))}
          </div>

          {/* Progress Bar */}
          <div className="mt-6 pt-6 border-t border-white/8">
            <div className="flex items-center justify-between mb-3">
              <span className="text-white/40 text-xs">Progress</span>
              <span className="text-white/60 text-xs font-medium">Step {currentStep + 1} of {instructions.length}</span>
            </div>
            <div className="bg-white/8 rounded-full h-1.5 mb-4 overflow-hidden">
              <div
                className="orange-gradient h-full rounded-full transition-all duration-300"
                style={{ width: `${((currentStep + 1) / instructions.length) * 100}%` }}
              />
            </div>
            <div className="flex gap-3">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setCurrentStep(s => Math.max(0, s - 1))}
                disabled={currentStep === 0}
                className="text-white/50 hover:text-white hover:bg-white/8 border border-white/10 flex-1"
              >
                <ChevronLeft className="w-4 h-4 mr-1" /> Previous
              </Button>
              <Button
                size="sm"
                onClick={() => setCurrentStep(s => Math.min(instructions.length - 1, s + 1))}
                disabled={currentStep === instructions.length - 1}
                className="orange-gradient text-white font-semibold flex-1"
              >
                Next <ChevronRight className="w-4 h-4 ml-1" />
              </Button>
            </div>
          </div>
        </div>

        {/* Completion CTA */}
        {currentStep === instructions.length - 1 && (
          <div className="card-premium rounded-xl p-8 mb-8 text-center border border-orange-500/20">
            <div className="w-16 h-16 rounded-full bg-orange-500/10 flex items-center justify-center mx-auto mb-4">
              <Zap className="w-8 h-8 text-orange-400" />
            </div>
            <h3 className="font-display text-xl font-extrabold text-white mb-2">
              Build Complete! 🔨
            </h3>
            <p className="text-white/50 text-sm mb-5 max-w-sm mx-auto">
              You made it through all {instructions.length} steps. Time to snap your finished build and show it off.
            </p>
            <Button onClick={handleShare} className="orange-gradient text-white font-semibold">
              <Share2 className="w-4 h-4 mr-2" />
              Share Your Build
            </Button>
          </div>
        )}

        {/* Feedback */}
        <div className="card-premium rounded-xl p-6">
          <FeedbackForm projectId={project.id} />
        </div>

    </main>
  );
}
