export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold text-[#1F4E79] mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Effective Date: March 1, 2026 · Last Updated: March 12, 2026</p>

      <div className="prose prose-slate max-w-none space-y-6 text-sm leading-relaxed">
        <p>Welcome to MyHandyman.ai. By accessing or using our service, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">1. Service Description</h2>
        <p>MyHandyman.ai is an AI-powered home repair assistant that analyzes photos or text descriptions of home repair issues and generates step-by-step repair guides, tool and material recommendations, time and cost estimates, and safety assessments. The service is operated by <strong>MyAiga LLC</strong>.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">2. Important Disclaimer — AI-Generated Advice</h2>
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
          <p className="font-semibold text-amber-800 mb-2">⚠️ Please Read Carefully</p>
          <p className="text-amber-900">MyHandyman.ai provides <strong>AI-generated repair guidance for informational purposes only</strong>. Our advice is NOT a substitute for professional assessment by a licensed contractor, electrician, plumber, or other qualified professional.</p>
          <ul className="list-disc pl-6 space-y-1 mt-2 text-amber-900">
            <li>Always consult a licensed professional for electrical work, gas line repairs, structural modifications, mold remediation, and any work requiring permits.</li>
            <li>AI analysis may not detect all hazards, code violations, or underlying issues.</li>
            <li>Follow all local building codes and obtain required permits for your area.</li>
            <li>When in doubt, hire a professional. Your safety is more important than saving money.</li>
          </ul>
        </div>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">3. Limitation of Liability</h2>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, MYAIGA LLC AND ITS OFFICERS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Your use of or reliance on AI-generated repair instructions</li>
          <li>Any injury, property damage, or loss resulting from attempting repairs based on our guidance</li>
          <li>Inaccuracies, errors, or omissions in the repair guides</li>
          <li>Any failure to identify safety hazards or code violations</li>
          <li>Service interruptions or unavailability</li>
        </ul>
        <p><strong>You acknowledge that home repair carries inherent risks and that you undertake any repairs at your own risk and responsibility.</strong></p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">4. Subscription Terms</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Free Tier:</strong> Limited number of AI repair analyses per month.</li>
          <li><strong>Premium Plan:</strong> $4.99/month for unlimited AI repair analyses and additional features.</li>
          <li>Subscriptions are billed monthly through Stripe and renew automatically.</li>
          <li>You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing period.</li>
          <li>No refunds are provided for partial billing periods.</li>
          <li>We reserve the right to change pricing with 30 days&apos; notice.</li>
        </ul>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the service for any illegal purpose</li>
          <li>Attempt to reverse-engineer, scrape, or extract our AI models or proprietary systems</li>
          <li>Upload harmful, offensive, or illegal content</li>
          <li>Use the service to generate advice for commercial contracting without proper licensing</li>
          <li>Abuse the free tier by creating multiple accounts to bypass usage limits</li>
          <li>Resell or redistribute repair guides generated by the service</li>
        </ul>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">6. Intellectual Property</h2>
        <p>The MyHandyman.ai service, including its design, logos, and AI technology, is the property of MyAiga LLC. Repair guides generated for you are provided for your personal use. You may share individual repair guides but may not systematically redistribute or commercialize them.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">7. Affiliate Links</h2>
        <p>Our repair guides include links to products on Amazon.com and potentially other retailers. These are affiliate links, meaning we may earn a commission on qualifying purchases. Product recommendations are generated by AI based on the repair requirements, not by advertising relationships. Prices and availability are determined by the retailers.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">8. Indemnification</h2>
        <p>You agree to indemnify and hold harmless MyAiga LLC from any claims, damages, losses, or expenses (including legal fees) arising from your use of the service or violation of these Terms.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">9. Termination</h2>
        <p>We reserve the right to suspend or terminate your access to the service at any time for violation of these Terms or for any reason at our discretion. Upon termination, your right to use the service ceases immediately.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">10. Governing Law</h2>
        <p>These Terms are governed by the laws of the State of Florida, without regard to conflict of law provisions. Any disputes shall be resolved in the courts of Palm Beach County, Florida.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">11. Changes to These Terms</h2>
        <p>We may update these Terms from time to time. Continued use of the service after changes constitutes acceptance of the new Terms.</p>

        <h2 className="text-xl font-semibold text-[#1F4E79] mt-8">12. Contact Us</h2>
        <p>If you have questions about these Terms, contact us at:</p>
        <p><strong>Email:</strong> <a href="mailto:support@myhandyman.ai" className="text-[#2FA3A0] hover:underline">support@myhandyman.ai</a></p>
        <p><strong>MyAiga LLC</strong><br />Palm Beach County, FL</p>
      </div>
    </div>
  );
}
