/**
 * scripts/generate-sitemap.ts
 *
 * Auto-generates client/public/sitemap.xml from the REPAIRS array in
 * client/src/content/repairs.ts. Run as part of the build pipeline so the
 * sitemap is always in sync with the live repair guides — no more manually
 * adding URLs and no more drift between repairs.ts and sitemap.xml.
 *
 * Run:  tsx scripts/generate-sitemap.ts
 * (called automatically from "build:frontend" in package.json)
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import { REPAIRS } from "../client/src/content/repairs.js";

const __filename = fileURLToPath(import.meta.url);
const __dir = dirname(__filename);
const ROOT = join(__dir, "..");
const OUT_PATH = join(ROOT, "client/public/sitemap.xml");

const SITE = "https://myhandyman.ai";

// Today's date in YYYY-MM-DD for <lastmod>
const today = new Date().toISOString().slice(0, 10);

type StaticEntry = {
  loc: string;
  changefreq: "daily" | "weekly" | "monthly" | "yearly";
  priority: string;
};

// Static (non-repair) routes. Add new top-level routes here.
const STATIC_ROUTES: StaticEntry[] = [
  { loc: "/", changefreq: "weekly", priority: "1.0" },
  { loc: "/repairs", changefreq: "weekly", priority: "0.8" },
  { loc: "/links", changefreq: "monthly", priority: "0.5" },
  // Vertical landing pages — added 2026-05-08 for Day 60 (6/21) vertical-pick
  // GA4 segmentation. Need 7+ days of indexed data before the read.
  { loc: "/florida-home-repair", changefreq: "weekly", priority: "0.8" },
  { loc: "/renter-repair-guide", changefreq: "weekly", priority: "0.8" },
  { loc: "/older-home-repair", changefreq: "weekly", priority: "0.8" },
];

const urlBlock = (loc: string, changefreq: string, priority: string) => `  <url>
    <loc>${SITE}${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;

// Dedupe slugs in case repairs.ts has any (it currently does — see #cleanup).
const seen = new Set<string>();
const repairBlocks: string[] = [];
for (const repair of REPAIRS) {
  if (seen.has(repair.slug)) continue;
  seen.add(repair.slug);
  repairBlocks.push(
    urlBlock(`/repairs/${repair.slug}`, "monthly", "0.7"),
  );
}

const staticBlocks = STATIC_ROUTES.map((r) =>
  urlBlock(r.loc, r.changefreq, r.priority),
);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by scripts/generate-sitemap.ts. Do not edit by hand. -->
<!-- To add a repair guide, add it to client/src/content/repairs.ts and rebuild. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

  <!-- Static routes -->
${staticBlocks.join("\n")}

  <!-- Repair guides (${seen.size} unique) -->
${repairBlocks.join("\n")}

</urlset>
`;

writeFileSync(OUT_PATH, xml, "utf8");
console.log(
  `[generate-sitemap] wrote ${OUT_PATH} — ${STATIC_ROUTES.length} static + ${seen.size} repair URLs`,
);
